version: '3'

services:

    transaction_db:
      image: mongo:4.4.4
      restart: unless-stopped
      container_name: transaction_db
      ports:
          - 27019:27017
      environment:
          - MONGO_INITDB_DATABASE=transactions
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          
    mongo_api:
      restart: unless-stopped
      container_name: api
      build:
        context: .
        dockerfile: Dockerfile
      ports: 
        - 9001:9001
      environment:
        - db_connection_string=mongodb://{0}:{1}@transaction_db:27017/{2}?authSource=admin&socketTimeoutMS=60000
      
      depends_on:
        - transaction_db